apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: todo-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
